In [2]:
%mamba install pandas

mambajs 0.21.1

Specs: xeus-python, numpy, matplotlib, pillow, ipywidgets>=8.1.6, ipyleaflet, scipy, pandas
Channels: emscripten-forge-4x, conda-forge

Solving environment...
Solving took 0.8658000000715256 seconds
  Name           Version  Build                Channel
--------------------------------------------------------------------
+ pandas         3.0.3    np23py313h1e705a5_0  emscripten-forge-4x
+ python-tzdata  2026.2   pyhd8ed1ab_0         conda-forge
- pip            26.1.2   pyh145f28c_0         conda-forge

In [3]:
import pandas as pd
import numpy as np

data = {
    'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
    'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
    'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']
}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

In [4]:
# 1. Створити DataFrame
df = pd.DataFrame(data)

In [5]:
# 2. Змінити індекси
df.index = labels

In [6]:
# 3. Значення в колонці 'animal', рядок з індексом 'e'
df.loc['e', 'animal']

'dog'

In [7]:
# 4. Кількість непорожніх значень у колонці 'age'
df['age'].count()

np.int64(8)

In [8]:
# 5. Перші 3 рядки таблиці
df.head(3)

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no

In [9]:
# 6. Рядки з позиціями 0, 2, 3
df.iloc[[0, 2, 3]]

  animal  age  visits priority
a    cat  2.5       1      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes

In [10]:
# 7. Тільки стовпці 'animal' та 'age'
df[['animal', 'age']]

  animal  age
a    cat  2.5
b    cat  3.0
c  snake  0.5
d    dog  NaN
e    dog  5.0
f    cat  2.0
g  snake  4.5
h    cat  NaN
i    dog  7.0
j    dog  3.0

In [11]:
# 8. Стовпці 'animal' та 'age', рядки з позиціями 0, 2, 3
df.iloc[[0, 2, 3]][['animal', 'age']]

  animal  age
a    cat  2.5
c  snake  0.5
d    dog  NaN

In [12]:
# 9. Рядки, де age > 3
df[df['age'] > 3]

  animal  age  visits priority
e    dog  5.0       2       no
g  snake  4.5       1       no
i    dog  7.0       2       no

In [13]:
# 10. Рядки, де age не є порожнім
df[df['age'].notna()]

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
i    dog  7.0       2       no
j    dog  3.0       1       no

In [14]:
# 11. Рядки, де age від 2 до 4 включно
df[df['age'].between(2, 4)]

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
f    cat  2.0       3       no
j    dog  3.0       1       no

In [15]:
# 12. Збільшити age на 1 для всіх тварин
df['age'] = df['age'] + 1

df

  animal  age  visits priority
a    cat  3.5       1      yes
b    cat  4.0       3      yes
c  snake  1.5       2       no
d    dog  NaN       3      yes
e    dog  6.0       2       no
f    cat  3.0       3       no
g  snake  5.5       1       no
h    cat  NaN       1      yes
i    dog  8.0       2       no
j    dog  4.0       1       no

In [24]:
# 13. Рядок з максимальним значенням age
df.loc[df['age'] == df['age'].max()]

  animal  age  visits priority
i    dog  8.0       2       no

In [25]:
# 14. Сума всіх значень у колонці 'age'
df.loc[:, 'age'].sum()

np.float64(35.5)

In [26]:
# 15. Рядки, де animal == 'cat'
df.loc[df['animal'] == 'cat']

  animal  age  visits priority
a    cat  3.5       1      yes
b    cat  4.0       3      yes
f    cat  3.0       3       no
h    cat  NaN       1      yes

In [27]:
# 16. Рядки, де animal == 'dog' і visits > 1
df.loc[(df['animal'] == 'dog') & (df['visits'] > 1)]

  animal  age  visits priority
d    dog  NaN       3      yes
e    dog  6.0       2       no
i    dog  8.0       2       no

In [28]:
# 17. Рядки, де priority == 'yes'
df.loc[df['priority'] == 'yes']

  animal  age  visits priority
a    cat  3.5       1      yes
b    cat  4.0       3      yes
d    dog  NaN       3      yes
h    cat  NaN       1      yes

In [29]:
# 18. Рядки, де priority == 'no' і age >= 3
df.loc[(df['priority'] == 'no') & (df['age'] >= 3)]

  animal  age  visits priority
e    dog  6.0       2       no
f    cat  3.0       3       no
g  snake  5.5       1       no
i    dog  8.0       2       no
j    dog  4.0       1       no

In [23]:
# 19. Колонки 'animal' та 'visits' де visits == 1
df.loc[df['visits'] == 1, ['animal', 'visits']]

  animal  visits
a    cat       1
g  snake       1
h    cat       1
j    dog       1

In [30]:
# 20. Рядки, де animal == 'cat' або 'snake'
df.loc[df['animal'].isin(['cat', 'snake'])]

  animal  age  visits priority
a    cat  3.5       1      yes
b    cat  4.0       3      yes
c  snake  1.5       2       no
f    cat  3.0       3       no
g  snake  5.5       1       no
h    cat  NaN       1      yes

In [32]:
# 21. Рядки, де age < 3 або age є порожнім
df.loc[(df['age'] < 3) | (df['age'].isna())]

  animal  age  visits priority
c  snake  1.5       2       no
d    dog  NaN       3      yes
h    cat  NaN       1      yes

In [33]:
# 22. Рядки, де visits від 2 до 3 включно
df.loc[df['visits'].between(2, 3)]

  animal  age  visits priority
b    cat  4.0       3      yes
c  snake  1.5       2       no
d    dog  NaN       3      yes
e    dog  6.0       2       no
f    cat  3.0       3       no
i    dog  8.0       2       no

In [34]:
# 23. Рядки де індекс == 'a', 'c' або 'f'
df.loc[['a', 'c', 'f']]

  animal  age  visits priority
a    cat  3.5       1      yes
c  snake  1.5       2       no
f    cat  3.0       3       no

In [35]:
# 24. Рядки де animal != 'dog'
df.loc[df['animal'] != 'dog']

  animal  age  visits priority
a    cat  3.5       1      yes
b    cat  4.0       3      yes
c  snake  1.5       2       no
f    cat  3.0       3       no
g  snake  5.5       1       no
h    cat  NaN       1      yes